django02/django2/django2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
]

django02/django2/vote/urls.py
from django.urls import path
from vote import views

app_name = 'vote'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django02/not_use/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    # path(r'^api/', include(router.urls)),
]

django02/django2/vote/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

django02/not_use/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

django02/django2/vote/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Choice, Question

# Create your views here.
def index(request):
    lastest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'lastest_question_list' : lastest_question_list}
    return render(request, 'vote/index.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'vote/detail.html', {
            'question' : question,
            'error_message' : "잘못된 선택입니다.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('vote:results', args=(question.id,)))
    # POST 데이터 처리 후 항상 HttpResponseRedirect로 사용자가 뒤로가기 버튼을 눌렀을 때, 중복 전달되는 것을 방지한다.

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vote/detail.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vote/results.html', {'question':question})

django02/django2/vote/templates/vote/detail.html
<form action="{% url 'vote:vote' question.id %}" method='post'>
{% csrf_token %}
    <fiendset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
            <br>
        {% endfor %}
    </fieldset>
    <input type='submit' value="Vote">
</form>

django02/django2/vote/templates/vote/index.html
{% if lastest_question_list %}
    <ul>
        {% for question in lastest_question_list%}
            <li>
                <a href='/vote/{{question.id}}'>{{question.question_text}}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>설문이 없습니다.</p>
{% endif %}

django02/django2/vote/templates/vote/results.html
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} ----> {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {# {% pluralize %} 해당 태그는 앞에 있는 choice.votes가 1보다 크면 s를 출력해준다. #}
    {% endfor %}
</ul>

<a href="{% url 'vote:detail' question.id%}"> 다시 투표하시겠습니까?</a>
    